{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "azuredevopskats.serviceAccountName" . }}
  labels:
    {{- include "azuredevopskats.labels" . | nindent 4 }}
{{- end }}
